const TODO = 'TODO'

export const TODO_ADD = `${TODO}/ADD`
export const TODO_DELETE = `${TODO}/DELETE`
export const TODO_EDIT = `${TODO}/EDIT`
export const TODO_COMPLETE = `${TODO}/COMPLETE`
export const TODO_COMPLETE_ALL = `${TODO}/COMPLETE_ALL`
export const TODO_CLEAR_COMPLETED = `${TODO}/CLEAR_COMPLETED`
export const TODO_SET_VISIBILITY_FILTER = `${TODO}/SET_VISIBILITY_FILTER`


const FILTERS = 'FILTERS'

export const FILTERS_SHOW_ALL = `${FILTERS}/SHOW_ALL`
export const FILTERS_SHOW_COMPLETED = `${FILTERS}/SHOW_COMPLETED`
export const FILTERS_SHOW_ACTIVE = `${FILTERS}/SHOW_ACTIVE`
